# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/brick
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

issues:
  # equivalent CLI flag: --exclude-use-default
  #
  # see:
  #   atc0005/brick#92
  #   golangci-lint/golangci-lint#1249
  #   golangci-lint/golangci-lint#413
  exclude-use-default: false

linters:
  enable:
    - dogsled
    - goimports
    - gosec
    - stylecheck
    - goconst
    - depguard
    - prealloc
    - misspell

    # Deprecated linter, but still functional as of golangci-lint v1.39.0.
    # See https://github.com/atc0005/go-ci/issues/302 for more information.
    - maligned

    - dupl
    - unconvert
    - gofmt
    - golint
    - gocritic
    - exportloopref

#
# Disable fieldalignment settings until the Go team offers more control over
# the types of checks provided by the fieldalignment linter or golangci-lint
# does so.
#
# See https://github.com/atc0005/go-ci/issues/302 for more information.
#

# disable:
# - maligned

# linters-settings:
# govet:
#   enable:
#     - fieldalignment
