# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/brick
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

issues:
  # equivalent CLI flag: --exclude-use-default
  #
  # see:
  #   atc0005/brick#92
  #   golangci-lint/golangci-lint#1249
  #   golangci-lint/golangci-lint#413
  exclude-use-default: false

linters:
  enable:
    # https://github.com/atc0005/go-ci/issues/1024
    # - depguard
    - dogsled
    - dupl
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - govet
    - maligned
    - misspell
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - unconvert
