# Copyright 2021 Adam Chalkley
#
# https://github.com/atc0005/brick
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Purpose:
#
# "Canary" Dockerfile for Go updates, monitored by Dependabot.
#
# After Dependabot provides a (valid) Pull Request to update this file, I
# should begin the process of preparing a new project release (including
# binaries) to reflect that version of Go.

# https://hub.docker.com/_/golang
FROM golang:1.21
