# Copyright 2022 Adam Chalkley
#
# https://github.com/atc0005/brick
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Lint and Build

# Run builds for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint_and_build_using_ci_matrix:
    name: CI matrix
    uses: atc0005/shared-project-resources/.github/workflows/lint-and-build-using-ci-matrix.yml@master

  lint_and_build_using_makefile:
    name: Makefile
    uses: atc0005/shared-project-resources/.github/workflows/lint-and-build-using-make.yml@master
