# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/brick
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Quick Validation

# Run builds for Pull Requests (new, updated)
# `synchronized` seems to equate to pushing new commits to a linked branch
# (whether force-pushed or not)
on:
  push:

jobs:
  lint_and_test_code:
    name: Lint and test using latest stable container
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: index.docker.io/atc0005/go-ci:go-ci-lint-only

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.3

      - name: Remove repo-provided golangci-lint config file
        run: |
          # Remove the copy of the config file bundled with the repo/code so
          # that the configuration provided by the atc0005/go-ci project is
          # used instead
          rm -vf .golangci.yml

      - name: Run golangci-lint using container-provided config file settings
        run: golangci-lint run -v

      - name: Run all tests
        run: go test -mod=vendor -v ./...
